# Generated by Django 5.2.7 on 2025-10-04 06:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imageupload_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=50, unique=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(default='1.0', max_length=20)),
                ('ethics_approval', models.CharField(default='BUIRB-2025-001', max_length=50)),
                ('age_group', models.CharField(blank=True, choices=[('18-25', '18-25 years'), ('26-35', '26-35 years'), ('36-45', '36-45 years'), ('46-55', '46-55 years'), ('56-65', '56-65 years'), ('65+', '65+ years'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('ethnicity', models.CharField(blank=True, choices=[('white', 'White/Caucasian'), ('black', 'Black/African American'), ('hispanic', 'Hispanic/Latino'), ('asian', 'Asian'), ('native-american', 'Native American'), ('middle-eastern', 'Middle Eastern'), ('mixed', 'Mixed/Multiracial'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=30)),
                ('skin_type', models.CharField(blank=True, choices=[('type-1', 'Type I - Very fair, always burns'), ('type-2', 'Type II - Fair, usually burns'), ('type-3', 'Type III - Medium, sometimes burns'), ('type-4', 'Type IV - Olive, rarely burns'), ('type-5', 'Type V - Brown, very rarely burns'), ('type-6', 'Type VI - Dark brown/black, never burns'), ('unsure', 'Unsure')], max_length=20)),
                ('education_level', models.CharField(blank=True, choices=[('high-school', 'High school or equivalent'), ('some-college', 'Some college'), ('bachelors', "Bachelor's degree"), ('masters', "Master's degree"), ('doctorate', 'Doctorate/PhD'), ('professional', 'Professional degree'), ('other', 'Other')], max_length=20)),
                ('medical_background', models.CharField(blank=True, choices=[('none', 'No medical background'), ('student', 'Medical student'), ('nurse', 'Nurse/Nursing'), ('doctor', 'Physician/Doctor'), ('dermatologist', 'Dermatologist'), ('researcher', 'Medical researcher'), ('other-medical', 'Other medical professional')], max_length=20)),
                ('ai_experience', models.CharField(blank=True, choices=[('none', 'No experience'), ('limited', 'Limited experience'), ('moderate', 'Moderate experience'), ('extensive', 'Extensive experience')], max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('phases_completed', models.JSONField(default=list)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ['-upload_timestamp']},
        ),
        migrations.RenameField(
            model_name='imageupload',
            old_name='uploaded_at',
            new_name='upload_timestamp',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='model_used',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='model_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='prediction',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserStudyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_rating', models.IntegerField(blank=True, choices=[(1, '1 - Not at all'), (2, '2 - Slightly'), (3, '3 - Moderately'), (4, '4 - Very much'), (5, '5 - Completely')], null=True)),
                ('usability_rating', models.IntegerField(blank=True, choices=[(1, '1 - Very difficult'), (2, '2 - Difficult'), (3, '3 - Neutral'), (4, '4 - Easy'), (5, '5 - Very easy')], null=True)),
                ('bias_perception', models.CharField(blank=True, choices=[('yes', 'Yes, definitely'), ('maybe', 'Possibly'), ('unsure', 'Unsure'), ('no', 'No, unlikely')], max_length=20)),
                ('improvements', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.userstudyparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='UserStudyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('image_size', models.IntegerField(blank=True, null=True)),
                ('image_type', models.CharField(blank=True, max_length=20)),
                ('prediction', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('analysis_order', models.IntegerField(default=1)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.userstudyparticipant')),
            ],
            options={
                'ordering': ['participant', 'analysis_order'],
            },
        ),
    ]
