# Generated by Django 5.2.3 on 2025-11-06 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userstudyparticipant_alter_imageupload_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FairnessAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('dataset_used', models.CharField(blank=True, max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('disparate_impact_ratio', models.FloatField(blank=True, null=True)),
                ('equalized_odds_difference', models.FloatField(blank=True, null=True)),
                ('demographic_parity_difference', models.FloatField(blank=True, null=True)),
                ('individual_fairness_score', models.FloatField(blank=True, null=True)),
                ('accuracy_by_skin_type', models.JSONField(default=dict)),
                ('confidence_by_demographic', models.JSONField(default=dict)),
                ('prediction_distribution', models.JSONField(default=dict)),
                ('overall_bias_level', models.CharField(blank=True, choices=[('low', 'Low Bias'), ('medium', 'Medium Bias'), ('high', 'High Bias'), ('critical', 'Critical Bias')], max_length=10)),
                ('mitigation_recommendations', models.TextField(blank=True)),
                ('analysis_notes', models.TextField(blank=True)),
                ('raw_results', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Fairness Analysis Result',
                'verbose_name_plural': 'Fairness Analysis Results',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ['-upload_timestamp'], 'verbose_name': 'Image Analysis Result', 'verbose_name_plural': 'Image Analysis Results & History'},
        ),
        migrations.AlterModelOptions(
            name='userstudyfeedback',
            options={'verbose_name': 'User Study Feedback', 'verbose_name_plural': 'User Study Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='userstudyparticipant',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Study Participant', 'verbose_name_plural': 'User Study Participants'},
        ),
        migrations.AddField(
            model_name='imageupload',
            name='is_user_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='recommendation',
            field=models.TextField(blank=True, help_text='AI-generated recommendation for user'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='research_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='result',
            field=models.CharField(blank=True, choices=[('cancer', 'Cancer Detected'), ('no_cancer', 'No Cancer'), ('suspected_cancer', 'Suspected Cancer'), ('unknown', 'Unknown/Unclear')], max_length=20),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('reviewed', 'Reviewed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userstudyfeedback',
            name='accuracy_perception',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very inaccurate'), (2, '2 - Inaccurate'), (3, '3 - Neutral'), (4, '4 - Accurate'), (5, '5 - Very accurate')], null=True),
        ),
        migrations.AddField(
            model_name='userstudyfeedback',
            name='concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userstudyfeedback',
            name='fairness_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very unfair'), (2, '2 - Unfair'), (3, '3 - Neutral'), (4, '4 - Fair'), (5, '5 - Very fair')], null=True),
        ),
        migrations.AddField(
            model_name='userstudyfeedback',
            name='positive_aspects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userstudyparticipant',
            name='research_consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DemographicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(blank=True, max_length=50)),
                ('location_region', models.CharField(blank=True, max_length=50)),
                ('has_skin_condition', models.BooleanField(default=False)),
                ('skin_condition_details', models.TextField(blank=True)),
                ('family_history_skin_cancer', models.BooleanField(default=False)),
                ('previous_skin_screening', models.BooleanField(default=False)),
                ('smartphone_usage', models.CharField(blank=True, choices=[('never', 'Never'), ('rarely', 'Rarely'), ('occasionally', 'Occasionally'), ('frequently', 'Frequently'), ('daily', 'Daily')], max_length=20)),
                ('health_app_usage', models.CharField(blank=True, choices=[('never', 'Never used'), ('tried', 'Tried once'), ('occasional', 'Occasional user'), ('regular', 'Regular user')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_profile', to='api.userstudyparticipant')),
            ],
            options={
                'verbose_name': 'Demographic Profile',
                'verbose_name_plural': 'Demographic Profiles',
            },
        ),
        migrations.CreateModel(
            name='ImageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_agreement', models.CharField(blank=True, choices=[('strongly_agree', 'Strongly Agree'), ('agree', 'Agree'), ('neutral', 'Neutral'), ('disagree', 'Disagree'), ('strongly_disagree', 'Strongly Disagree')], max_length=20)),
                ('confidence_rating', models.IntegerField(blank=True, choices=[(1, '1 - Very low confidence'), (2, '2 - Low confidence'), (3, '3 - Medium confidence'), (4, '4 - High confidence'), (5, '5 - Very high confidence')], null=True)),
                ('helpfulness_rating', models.IntegerField(blank=True, choices=[(1, '1 - Not helpful'), (2, '2 - Slightly helpful'), (3, '3 - Moderately helpful'), (4, '4 - Very helpful'), (5, '5 - Extremely helpful')], null=True)),
                ('specific_feedback', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_feedbacks', to='api.imageupload')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userstudyparticipant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Feedback',
                'verbose_name_plural': 'Image Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='ResearchConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_form_version', models.CharField(default='v1.0', max_length=20)),
                ('ethics_approval_number', models.CharField(default='BUIRB-2025-001', max_length=50)),
                ('data_collection_consent', models.BooleanField(default=False)),
                ('data_analysis_consent', models.BooleanField(default=False)),
                ('publication_consent', models.BooleanField(default=False)),
                ('future_contact_consent', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(auto_now_add=True)),
                ('consent_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_withdrawn', models.BooleanField(default=False)),
                ('withdrawal_date', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_consent', to='api.userstudyparticipant')),
            ],
            options={
                'verbose_name': 'Research Consent',
                'verbose_name_plural': 'Research Consents',
            },
        ),
        migrations.CreateModel(
            name='SystemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('usability', 'Usability Issue'), ('performance', 'Performance Issue'), ('accuracy', 'Accuracy Concern'), ('general', 'General Feedback')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField(blank=True)),
                ('expected_behavior', models.TextField(blank=True)),
                ('actual_behavior', models.TextField(blank=True)),
                ('browser_info', models.TextField(blank=True)),
                ('device_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Feedback',
                'verbose_name_plural': 'System Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('image_analysis', 'Image Analysis'), ('feedback', 'Feedback Collection'), ('follow_up', 'Follow-up')], max_length=20)),
                ('activities_completed', models.JSONField(default=list)),
                ('images_analyzed', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('issues_encountered', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='api.userstudyparticipant')),
            ],
            options={
                'verbose_name': 'User Study Session',
                'verbose_name_plural': 'User Study Sessions',
                'ordering': ['-session_start'],
            },
        ),
        migrations.DeleteModel(
            name='UserStudyAnalysis',
        ),
    ]
