# Generated by Django 5.2.7 on 2025-10-04 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitzpatrick_skin_type', models.CharField(blank=True, choices=[('I', 'Type I - Very fair (always burns, never tans)'), ('II', 'Type II - Fair (usually burns, tans minimally)'), ('III', 'Type III - Medium (sometimes burns, tans gradually)'), ('IV', 'Type IV - Olive (rarely burns, tans well)'), ('V', 'Type V - Brown (very rarely burns, tans very easily)'), ('VI', 'Type VI - Dark brown/Black (never burns, tans very easily)'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('age_group', models.CharField(blank=True, choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56-65', '56-65'), ('65+', '65+'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High school or equivalent'), ('bachelors', "Bachelor's degree"), ('masters', "Master's degree"), ('phd', 'PhD or equivalent'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('has_skin_condition', models.BooleanField(default=False, help_text='Do you have any known skin conditions?')),
                ('previous_ai_experience', models.BooleanField(default=False, help_text='Have you used AI-based diagnostic tools before?')),
                ('consent_for_research', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_in_prediction', models.IntegerField(choices=[(1, 'Not at all trustworthy'), (2, 'Slightly trustworthy'), (3, 'Moderately trustworthy'), (4, 'Very trustworthy'), (5, 'Extremely trustworthy')])),
                ('confidence_in_system', models.IntegerField(choices=[(1, 'Not confident at all'), (2, 'Slightly confident'), (3, 'Moderately confident'), (4, 'Very confident'), (5, 'Extremely confident')])),
                ('would_act_on_result', models.BooleanField(help_text='Would you act on this prediction?')),
                ('perceived_accuracy', models.IntegerField(help_text='Rate the perceived accuracy (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('noticed_bias', models.BooleanField(default=False, help_text='Did you notice any bias in the result?')),
                ('bias_description', models.TextField(blank=True, help_text='Describe any bias you noticed')),
                ('ease_of_use', models.IntegerField(help_text='How easy was it to use the system? (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('interface_clarity', models.IntegerField(help_text='How clear was the interface? (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_to_participate', models.BooleanField(default=False)),
                ('consent_data_collection', models.BooleanField(default=False)),
                ('consent_image_analysis', models.BooleanField(default=False)),
                ('consent_demographic_data', models.BooleanField(default=False)),
                ('consent_feedback_publication', models.BooleanField(default=False)),
                ('data_retention_years', models.IntegerField(default=5)),
                ('can_withdraw_consent', models.BooleanField(default=True)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_is_reliable', models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')])),
                ('system_is_fair', models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')])),
                ('system_respects_diversity', models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')])),
                ('would_recommend', models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')])),
                ('works_equally_all_skin_tones', models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')], help_text='The system works equally well for all skin tones')),
                ('free_from_discrimination', models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')], help_text='The system is free from discrimination')),
                ('inclusive_design', models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')], help_text='The system has an inclusive design')),
                ('trust_in_ai_diagnosis', models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly agree')], help_text='I trust AI-based diagnosis tools')),
                ('trust_compared_to_doctor', models.IntegerField(help_text='Trust level compared to human doctor (1=much less, 5=much more)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('most_concerning_aspect', models.TextField(blank=True, help_text='What concerns you most about AI-based skin diagnosis?')),
                ('improvement_suggestions', models.TextField(blank=True, help_text='How could this system be improved?')),
                ('overall_experience', models.TextField(blank=True, help_text='Describe your overall experience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
