# Generated by Django 5.2.7 on 2025-10-04 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='image_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.imageupload'),
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchconsent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_consent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstudysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemfeedback',
            name='study_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_feedback', to='feedback.userstudysession'),
        ),
        migrations.AddField(
            model_name='imagefeedback',
            name='study_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_feedback', to='feedback.userstudysession'),
        ),
    ]
